/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './message.component.ngfactory';
import * as import2 from './message.component';
import * as import3 from './message.service';
import * as import4 from '@angular/common';
import * as import5 from './message-list.component';
const styles_MessageListComponent:any[] = ([] as any[]);
export const RenderType_MessageListComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_MessageListComponent,
  data: {}
}
);
function View_MessageListComponent_1(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-message',([] as any[]),(null as any),(null as any),(null as any),import1.View_MessageComponent_0,import1.RenderType_MessageComponent)),
      import0.ɵdid(24576,(null as any),0,import2.MessageComponent,[import3.MessageService],{message: [
        0,
        'message'
      ]
    },(null as any))
  ]
  ,(ck,v) => {
    const currVal_0:any = v.context.$implicit;
    ck(v,1,0,currVal_0);
  },(null as any));
}
export function View_MessageListComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'col-md-8 col-md-offset-2'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n      '])),
    (l()(),import0.ɵand(8388608,(null as any),(null as any),1,(null as any),View_MessageListComponent_1)),
    import0.ɵdid(401408,(null as any),0,import4.NgForOf,[
      import0.ViewContainerRef,
      import0.TemplateRef,
      import0.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(ck,v) => {
    var co:import5.MessageListComponent = v.component;
    const currVal_0:any = co.messages;
    ck(v,4,0,currVal_0);
  },(null as any));
}
function View_MessageListComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-message-list',([] as any[]),(null as any),(null as any),(null as any),View_MessageListComponent_0,RenderType_MessageListComponent)),
    import0.ɵdid(57344,(null as any),0,import5.MessageListComponent,[import3.MessageService],(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const MessageListComponentNgFactory:import0.ComponentFactory<import5.MessageListComponent> = import0.ɵccf('app-message-list',import5.MessageListComponent,View_MessageListComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTGVuMTU5L0Rlc2t0b3AvU3R1ZGRpZXMvVWRlbXkvTUVBTiAyL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2UtbGlzdC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvTGVuMTU5L0Rlc2t0b3AvU3R1ZGRpZXMvVWRlbXkvTUVBTiAyL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2UtbGlzdC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9MZW4xNTkvRGVza3RvcC9TdHVkZGllcy9VZGVteS9NRUFOIDIvc2VlZC1wcm9qZWN0L2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZS1saXN0LmNvbXBvbmVudC50cy5NZXNzYWdlTGlzdENvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvTGVuMTU5L0Rlc2t0b3AvU3R1ZGRpZXMvVWRlbXkvTUVBTiAyL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2UtbGlzdC5jb21wb25lbnQudHMuTWVzc2FnZUxpc3RDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICA8ZGl2IGNsYXNzPVwiY29sLW1kLTggY29sLW1kLW9mZnNldC0yXCI+XG4gICAgICA8YXBwLW1lc3NhZ2VcbiAgICAgICAgW21lc3NhZ2VdPVwibWVzc2FnZVwiXG4gICAgICAgICpuZ0Zvcj1cImxldCBtZXNzYWdlIG9mIG1lc3NhZ2VzXCI+PC9hcHAtbWVzc2FnZT5cbiAgICA8L2Rpdj5cbiAgIiwiPGFwcC1tZXNzYWdlLWxpc3Q+PC9hcHAtbWVzc2FnZS1saXN0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDRU07a0JBQUE7UUFBQTtRQUFBO01BQUE7SUFBQTs7O0lBQ0U7SUFERixTQUNFLFNBREY7Ozs7O0lBRk47TUFDSTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXNDO0lBQ3BDO2dCQUFBOzs7O0lBQUE7T0FBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBRWlEO0lBQzdDOzs7O0lBREY7SUFGRixTQUVFLFNBRkY7Ozs7O0lDRk47Z0JBQUE7OztJQUFBOzs7In0=
